"""empty message

Revision ID: 161789f65770
Revises: 
Create Date: 2022-05-31 09:28:29.350335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161789f65770'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('cpf', sa.String(length=15), nullable=True),
    sa.Column('telefone', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rua', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('complemento', sa.String(length=200), nullable=False),
    sa.Column('cep', sa.String(length=50), nullable=False),
    sa.Column('bairro', sa.String(length=200), nullable=False),
    sa.Column('cidade', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('velocidade', sa.String(length=50), nullable=False),
    sa.Column('preco', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('disponibilidade', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto')
    op.drop_table('inventario')
    op.drop_table('endereco')
    op.drop_table('cliente')
    # ### end Alembic commands ###
