"""empty message

Revision ID: 397328e0606c
Revises: 161789f65770
Create Date: 2022-05-31 09:51:50.096867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397328e0606c'
down_revision = '161789f65770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente_inventario',
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('inventario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['inventario_id'], ['inventario.id'], ),
    sa.PrimaryKeyConstraint('cliente_id', 'inventario_id')
    )
    op.create_table('produto_inventario',
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('inventario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inventario_id'], ['inventario.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('produto_id', 'inventario_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto_inventario')
    op.drop_table('cliente_inventario')
    # ### end Alembic commands ###
