"""empty message

Revision ID: bacdafbe4ec4
Revises: b9fe41eb0e67
Create Date: 2022-05-16 23:01:57.488723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bacdafbe4ec4'
down_revision = 'b9fe41eb0e67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endereco', sa.Column('bairro', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endereco', 'bairro')
    # ### end Alembic commands ###
